name: 'AWS Secrets Manager Action3'
author: 'Abhilash Kishore'
description: 'Use secrets from AWS Secrets Manager as environment variables in your GitHub Actions workflow'
inputs:
  secrets:
    description: 'List of secret names you want to fetch secret values for'
    required: false
    default: ''
  mapped-secrets:
    description: 'List of mapped secret options. I.e. [{"prefix": "MY", "secret": "secret_name"}]. JSON keys from secret are mapped using prefix to env variables.'
    required: false
    default: '[]'
  parse-json:
    description: 'If true and secret values are stringified JSON objects, they will be parsed and flattened. Its key value pairs will become individual secrets'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: lock
  color: blue
